services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 9000:9000

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network

# Additional network for internal services
#   homelab:
#     name: homelab
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.19.0.0/24
